#!/bin/bash

if [ "$1" == "" ]; then
	echo "Error: No version provided"
	echo "./makebeta 0.0.1b1"
	exit 1
fi

clear
branch=$(git rev-parse --abbrev-ref HEAD)
read -p "Current branch is $branch. Continue ? (y/N)" choice
case "$choice" in 
  n|N|'' )
    echo "Cancel !"
    exit 1
  ;;
  y|Y ) echo "Make beta...";;
  * )
    echo "Cancel !"
    exit 1
  ;;
esac



# Ready to update :

git branch beta
git checkout beta

version=$1

sed -i "/\"version\":/c\ \ \"version\": \"$version\"," src/manifest.json

git commit -a -m "Beta Version $version"

cd src
zip -r ../quickdial-beta-$version.zip . -x src.zip
cd ..

git checkout $branch
git branch -D beta

